import{A as k}from"./assets/vendor-DwbG9ayR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))o(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function n(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(s){if(s.ep)return;s.ep=!0;const r=n(s);fetch(s.href,r)}})();document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".theme-switch__checkbox"),t=document.documentElement;if(!e){console.warn("Theme switch element not found");return}const n=o=>{t.setAttribute("data-theme",o?"dark":"light"),e.checked=o};try{n(!1);const o=localStorage.getItem("theme");o==="dark"?n(!0):o||window.matchMedia("(prefers-color-scheme: dark)").matches&&n(!0),window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",r=>{localStorage.getItem("theme")||n(r.matches)}),e.addEventListener("change",()=>{const r=e.checked;n(r),localStorage.setItem("theme",r?"dark":"light")})}catch(o){console.error("Error in theme initialization:",o)}});const b=["HTML/CSS","JavaScript","React","Node. js","React Native","Typescript","HTML/CSS","JavaScript","React","Node. js","React Native","Typescript"],l=document.querySelector(".marquee-inner"),p=document.querySelector(".marquee-inner-rotate");l.insertAdjacentHTML("beforeend",w(b));p.insertAdjacentHTML("beforeend",M(b));l.addEventListener("click",x);p.addEventListener("click",x);l.addEventListener("mouseenter",L);l.addEventListener("mouseleave",E);p.addEventListener("mouseenter",L);p.addEventListener("mouseleave",E);let u;function w(e){return e.map(t=>`
    <span class="marquee-line">${t}</span>
    <span class="marquee-dot"></span>
    `).join("")}function M(e){return e.map(t=>`
    <span class="marquee-line-rotate">${t}</span>
    <span class="marquee-dot-rotate"></span>
    `).join("")}function v(e){if(!e)return;const t=e.innerHTML;e.innerHTML+=t}v(l);v(p);function x(){this.classList.toggle("paused")}function L(e){clearTimeout(u);const t=e.currentTarget;u=setTimeout(()=>{t.style.animationDirection="reverse"},200)}function E(e){clearTimeout(u);const t=e.currentTarget;u=setTimeout(()=>{t.style.animationDirection="normal"},200)}const T="/images/my-projects/sprite.svg";k.init();const f=[{src1x:"./my-projects/rectangle-11-1x.jpg",src2x:"./my-projects/rectangle-11-2x.jpg",src:"./my-projects/rectangle-11-1x.jpg",alt:"Wallet webservice",link:"https://github.com/sselesnes/project-group-09"},{src1x:"./my-projects/rectangle-9-1x.jpg",src2x:"./my-projects/rectangle-9-2x.jpg",src:"./my-projects/rectangle-9-1x.jpg",alt:"Green harvest webservice",link:"https://github.com/sselesnes/project-group-09"},{src1x:"./my-projects/rectangle-12-1x.jpg",src2x:"./my-projects/rectangle-12-2x.jpg",src:"./my-projects/rectangle-12-1x.jpg",alt:"English Excellence website",link:"https://github.com/sselesnes/project-group-09"},{src1x:"./my-projects/rectangle-10-1x.jpg",src2x:"./my-projects/rectangle-10-2x.jpg",src:"./my-projects/rectangle-10-1x.jpg",alt:"Power Pulse webservice",link:"https://github.com/sselesnes/project-group-09"},{src1x:"./my-projects/rectangle-7-1x.jpg",src2x:"./my-projects/rectangle-7-2x.jpg",src:"./my-projects/rectangle-7-1x.jpg",alt:"Mimino website",link:"https://github.com/sselesnes/project-group-09"},{src1x:"./my-projects/rectangle-8-1x.jpg",src2x:"./my-projects/rectangle-8-2x.jpg",src:"./my-projects/rectangle-8-1x.jpg",alt:"Vyshyvanka Vibes Landing Page",link:"https://github.com/sselesnes/project-group-09"},{src1x:"./my-projects/rectangle-6-1x.jpg",src2x:"./my-projects/rectangle-6-2x.jpg",src:"./my-projects/rectangle-6-1x.jpg",alt:"Chego Jewelry website",link:"https://github.com/sselesnes/project-group-09"},{src1x:"./my-projects/rectangle-4-1x.jpg",src2x:"./my-projects/rectangle-4-2x.jpg",src:"./my-projects/rectangle-4-1x.jpg",alt:"Energy Flow webservice",link:"https://github.com/sselesnes/project-group-09"},{src1x:"./my-projects/rectangle-5-1x.jpg",src2x:"./my-projects/rectangle-5-2x.jpg",src:"./my-projects/rectangle-5-1x.jpg",alt:"Fruitbox online store",link:"https://github.com/sselesnes/project-group-09"},{src1x:"./my-projects/first-screen-1-1x.jpg",src2x:"./my-projects/first-screen-1-2x.jpg",src:"./my-projects/first-screen-1-1x.jpg",alt:"Starlight Studio Landing Page",link:"https://github.com/sselesnes/project-group-09"}],h="/project-group-09/",y=document.querySelector(".gallery"),i=document.querySelector(".btn-load-more-my-project");let d=0;const q=3;function A(e){const t=e.map(({src1x:n,src2x:o,src:s,alt:r,link:a})=>`
      <li>
        <a href="${a}" class="gallery-link" target="_blank" rel="noopener noreferrer">
          <img data-aos="flip-up" data-aos-duration="500" data-aos-easing="linear"
            class="image-my-project" srcset="${h}${n} 1x, ${h}${o} 2x"
            src="${h}${s}" alt="${r}" />
        </a>
        <p class="text-my-project">React, JavaScript, Node JS, Git</p>
        <div class="div-my-project"
          data-aos="fade-up"
          data-aos-anchor-placement="bottom-bottom"
          data-aos-easing="linear"
          data-aos-duration="500">
          <h3 class="names-my-project">${r}</h3>
          <button class="button-my-project" onclick="window.open('${a}', '_blank')">
            <span class="visit-my-project">VISIT</span>
            <svg class="svg-my-project" height="24" width="24">
              <use class="svg-visit-my-project" href="${T}#icon-visit-arrow"></use>
            </svg>
          </button>
        </div>
      </li>
      `).join("");y.insertAdjacentHTML("beforeend",t)}async function S(e=!0){i.disabled=!0,i.classList.add("disabled");const t=f.slice(d,d+q),n=y.lastElementChild;await new Promise(s=>setTimeout(s,200)),A(t);const o=n?n.nextElementSibling:y.firstElementChild;e&&o&&o.scrollIntoView({behavior:"smooth",block:"start"}),d+=t.length,d>=f.length?i.style.display="none":(i.disabled=!1,i.classList.remove("disabled"))}i.addEventListener("click",S);S(!1);document.addEventListener("DOMContentLoaded",()=>{try{let s=function(){try{if(typeof particlesJS>"u"){console.error("particlesJS is not loaded");return}if(!document.getElementById("particles-js")){console.error("particles-js container not found");return}particlesJS("particles-js",{particles:{number:{value:80,density:{enable:!0,value_area:800}},color:{value:["#00B068","#14c57c","#009156"]},shape:{type:"circle"},opacity:{value:.5,random:!0},size:{value:3,random:!0},line_linked:{enable:!0,distance:150,color:"#00B068",opacity:.4,width:1},move:{enable:!0,speed:2,direction:"none",random:!0,straight:!1,out_mode:"out",bounce:!1}},interactivity:{detect_on:"canvas",events:{onhover:{enable:!0,mode:"grab"},onclick:{enable:!0,mode:"push"},resize:!0},modes:{grab:{distance:140,line_linked:{opacity:1}},push:{particles_nb:4}}},retina_detect:!0})}catch(c){console.error("Error initializing particles:",c)}},r=function(){try{typeof pJSDom<"u"&&pJSDom.length>0&&(pJSDom[0].pJS.fn.vendors.destroypJS(),pJSDom=[])}catch(c){console.error("Error destroying particles:",c)}};const e=document.querySelector(".burger-menu"),t=document.querySelector(".mobile-menu"),n=document.querySelector(".mobile-close"),o=document.body;if(!e||!t||!n){console.warn("Not all mobile menu elements found");return}e.addEventListener("click",()=>{try{t.classList.add("is-open"),e.classList.add("is-open"),o.classList.add("menu-open"),s()}catch(c){console.error("Error opening menu:",c)}}),n.addEventListener("click",()=>{try{t.classList.remove("is-open"),e.classList.remove("is-open"),o.classList.remove("menu-open"),r()}catch(c){console.error("Error closing menu:",c)}}),t.querySelectorAll(".nav-link").forEach(c=>{c.addEventListener("click",()=>{try{t.classList.remove("is-open"),e.classList.remove("is-open"),o.classList.remove("menu-open"),r()}catch(g){console.error("Error closing menu on link click:",g)}})}),document.querySelectorAll('a[href^="#"]').forEach(c=>{c.addEventListener("click",function(g){try{g.preventDefault();const m=this.getAttribute("href"),j=document.querySelector(m);j?j.scrollIntoView({behavior:"smooth",block:"start"}):console.warn(`Element with id ${m} not found`)}catch(m){console.error("Error during smooth scroll:",m)}})})}catch(e){console.error("Critical error in mobile menu initialization:",e)}});
//# sourceMappingURL=index.js.map
